# aedenmurray.io CI
# prettier-ignore

jobs:
  build-website:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout

      - run:
          name: 'Install dependencies'
          command: |
            sudo apt update
            sudo apt install awscli
            npm install


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-website:
          filters:
            branches:
              only:
                - master
