# aedenmurray.io CI
# prettier-ignore
version: 2.1

jobs:
  build-website:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout

      - run:
          name: 'Install dependencies'
          command: |
            npm install

      - run:
          name: 'Build website'
          command: |
            npm run build

      - persist_to_workspace:
          root: ~/project
          paths: dist

  deploy-website:
    docker:
      - image: cimg/node:15.3.0

    steps:
      - attach_workspace:
          at: dist

      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install awscli

      - run:
          name: Sync to S3
          command: |
            aws s3 sync dist/ s3://aedenmurray.io --delete

      - run:
          name: Create invalidation
          command: |
            aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID --paths '/*'



workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-website:
          filters:
            branches:
              only:
                - master
      - deploy-website:
          context: 
            - AWS
          requires:
            - build-website
