# aedenmurray.io CI
# prettier-ignore

jobs:
  build-website:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout

      - run:
          name: 'Install dependencies'
          command: |
            npm install

  deploy-website:
    steps:
      - run:
          name: 'x'
          command: ls


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-website:
          filters:
            branches:
              only:
                - master
      - deploy-website:
          requires:
            - build-website
